name: Check and Build

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  merge_group:

permissions:
  contents: read

env:
  JAVA_DISTRIBUTION: zulu
  JAVA_VERSION: "17"

jobs:
  lint:
    name: Spotless check
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Check out code
        uses: actions/checkout@v7

      - &setup-jdk
        name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - &setup-gradle
        name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6.2.0

      - &prepare-gradle
        name: Prepare Gradle wrapper
        run: |
          tr -d '\r' < gradlew > gradlew.tmp && mv gradlew.tmp gradlew
          chmod +x ./gradlew

      - name: Spotless
        run: ./gradlew spotlessCheck

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-jdk
      - *setup-gradle

      - &setup-android
        name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - *prepare-gradle

      - name: Test
        run: ./gradlew test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-jdk
      - *setup-gradle
      - *setup-android
      - *prepare-gradle

      - name: Build with Gradle
        run: ./gradlew buildDevDebug
